export *  from './CheckOut/CheckOut';
export *  from './CreateAccount/CreateAccount';
export *  from './Home/Home';
export *  from './MyAccount/MyAccount';
export *  from './NewPassword/NewPassword';
export *  from './NotFound/NotFound';
export *  from './Orders/Orders';
export *  from './PasswordRecovery/PasswordRecover';
export *  from './SendEmail/SendEmail';